Colab (Notebook)
* Colab - Google's version of Jupyter Notebook
* Cell - Text / Code
* Texts are mostly in markdown format
* Run - Cell by Cell; Sequence - the way you run

Python:
* interpreter (vs compiler)
* No Defining Variable Type
* No semicolon at the end
* indentation (scope)



---



---

<font color = 'skyblue'>**Basic Python Syntax**</font>

In [ ]:
x = 5     # variable declaration, A variable is created the moment you first assign a value to it.
print(x)
print(type(x))

x = "Machine Learning"  # variable can hold different types of values
print(x)
print(type(x))

5
<class 'int'>
Machine Learning
<class 'str'>

In [ ]:
#Python allows you to assign values to multiple variables in one line:
a, b, c = "vaiarble1", "variable2", "varaibel3"
print(a,b,c)

#Concatenation:
x = "Machine Learning"
print("This is a" + x + "lab")

vaiarble1 variable2 varaibel3
This is aMachine Learninglab

In [ ]:
print("This is a",  x , "lab")

This is a Machine Learning lab

In [ ]:
a = 5**3 # exponential
print(a)

a = 5/3   # true division
print(a)

a = 5//3
print(a) # the floor division // rounds the result down to the nearest Integer

15
1.6666666666666667
1

<font color = 'orange'>*Conditional statements*</font>

In [ ]:
a=0

if a<0:
  print('a is negative')
elif a>0:
  print('a is positive')
else:
  print('a is zero')

a is zero

<font color = 'lightgreen'>*Functions and Scopes*</font>

In [ ]:
# defining a function and a global variable

def add(a, b):
  x= a+b

print(add(5,2))

7


<font color = 'lightgreen'>*Commonly used data types*</font><br>


*Text*:	str <br>
*Numeric*:	int, float, complex <br>
*Sequential*:	list, tuple, range <br>
*Map*:	dict <br>
*Set*:	set, frozenSet <br>
*Boolean*:	bool <br>
*Binary*:	bytes, byteArray, memoryView

<font color = 'lightpink'>*Data types and type casting*</font>

In [ ]:
x = 5.98

In [ ]:
print(type(str(5)))

<class 'str'>

In [ ]:
x = 1 # int
y = 2.8 # float
z = 1j # complex

#convert from int to float:
a = float(x)
print(type(a))

#convert from float to int:
b = int(y)
print(type(b))

#convert from int to complex:
c = complex(x)
print(type(c))

<class 'float'>
<class 'int'>
<class 'complex'>

In [ ]:
#casting in python

x= int("5")
print(x,type(x))

y = str(5.0)
print(y,type(y))

5 <class 'int'>
5.0 <class 'str'>

In [ ]:
var = input("Enter a number")
print(type(var))

Enter a number67
<class 'str'>

<font color='lightpink'>*Basic string operations*</font>

In [ ]:
str1 = " Single line string  " # single line
print(str1.rstrip())

 Single line string

In [ ]:
# Python strings are zero-indexed

str0 = 'Abid\'s home'
str1 = " Single \n line string" # single line

str2 = """ multiline
 string """ # multi-line string

print(str1)
print(str1.strip()) # The strip() method removes any whitespace from the beginning or the end

print(str1)
print(str2)

 Single
 line string
Single
 line string
 Single
 line string
 multiline
 string

In [ ]:
str1 = "Single line string"
strs = str1.split(' ')    ## returns a list
print(strs)

['Single', 'line', 'string']

<font color = 'orange'>*negative indexing &
slicing*</font>

In [ ]:
dummy = "Nationality"
# Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.
print(dummy[-4])

l

In [ ]:
dummy = "Nationality"
# Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.
print(dummy[1])

# Slicing: You can return a range of characters by using the slice syntax.
print(dummy[2:6]) # let 2 is the 1st argument and 6 is the 2nd argument.
                 # It will print characters ranging from the 1st argument upto (2nd argument - 1).

# Negative Indexing: Use negative indexes to start the slice from the end of the string:
print(dummy[-2])
print(dummy[-5:])

a
tion
t
ality

In [ ]:
dummy[:6]

'Nation'

In [ ]:
print(len(str1))  #The len() function returns the length of a string:

print(str1.lower())
print(str1.upper())

19
 single line string
 SINGLE LINE STRING

<font color = 'orange'>*dir*</font>

In [ ]:
str1 = "abc"
print(dir(str1))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [ ]:
str1="abc"
print(str1.isdigit())

False

<font color = 'orange'>*Operators*</font>

In [ ]:
#identity operators

x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z) # returns True because z is the same object as x

print(x is y) # returns False because x is not the same object as y, even if they have the same content

print(x == y) # to demonstrate the difference betweeen "is" and "==": this comparison returns True because x is equal to y

print(x is not z) # returns False because z is the same object as x

print(x is not y) # returns True because x is not the same object as y, even if they have the same content

print(x != y)
# to demonstrate the difference betweeen "is not" and "!=": this comparison returns False because x is equal to y

True
False
True
False
True
False

In [ ]:
## membership operator

x = ["apple", "banana"]
y = ["apple", "banana"]

print("pineapple"  in x)
print("pineapple" not in y)

# returns True because a sequence with the value "pineapple" is not in the list

False
True

<font color = orange>*Collections - Arrays*<br></font>
There are four collection data types in the Python programming language. <br>


1.   **List**: A collection which is ordered and changeable. Allows duplicate members. Python lists are written with square brackets.
2.   **Tuple**: A collection which is ordered and unchangeable. Allows duplicate members. Tuples are written with round brackets.
3.   **Set**: A collection which is unordered and unindexed. No duplicate members.
4.   **Dictionary**: A collection which is unordered, changeable and indexed. No duplicate members.

*List*

In [ ]:
l1 = ["sdf", "a", 5.6, 11]
print(l1)

['sdf', 'a', 5.6, 11]

In [ ]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"] # Initializing a list
thislist = list(("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")) # Creating list using list constructor
print(thislist)
print(thislist[2]) # Postive indexing
print(thislist[-1]) # Negative indexing
print(thislist[1:5]) # The search will start at index 1 (included) and end at index 5 (not included).
print(thislist[:5])
print(thislist[-4:-1])
print(len(thislist)) #length of the list

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
cherry
mango
['banana', 'cherry', 'orange', 'kiwi']
['apple', 'banana', 'cherry', 'orange', 'kiwi']
['orange', 'kiwi', 'melon']
7

In [ ]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
L = ''.join(thislist)
print(L)

L = ' '.join(thislist)
print(L)

L = ';'.join(thislist)
print(L)

applebananacherryorangekiwimelonmango
apple banana cherry orange kiwi melon mango
apple;banana;cherry;orange;kiwi;melon;mango

In [ ]:
thislist.sort() # Sorting the list
print(thislist)
thislist.reverse() # Reversing the order of the list
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'mango', 'melon', 'orange']
['orange', 'melon', 'mango', 'kiwi', 'cherry', 'banana', 'apple']

In [ ]:
cherryIndex= thislist.index("cherry") # The index() method returns the position at the first occurrence of the specified value.
cherryCount = thislist.count("cherry") # Returns the number of elements with the specified value.
print(cherryIndex, cherryCount)

4 1

In [ ]:
thislist[1]= "jackfruit" # Replacing item
print(thislist)

thislist.insert(1, "pomegranate")  # Inserting at a specified position
print(f'After inserting at 1 - {thislist}')

thislist.append("jackfruit") #insert at the end
print(thislist)

['orange', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple']
After inserting at 1 - ['orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple']
['orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple', 'jackfruit']

In [ ]:
thislist1 = list(thislist) # Making a copy of the list
thislist2 = thislist.copy() #Making a copy of the list

thislist.remove("jackfruit") # The remove() method removes the first matching element from the list.
print(thislist)
thislist.pop(2) # Removing item from specified index
print(thislist)
thislist.clear() # Empties the item of the list
print(thislist)

del thislist # Deletes the list

In [ ]:
thislist3 = thislist1 + thislist2 # Joining two list
print(thislist3)

thislist1.extend(thislist2)
print(thislist1)

['orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple', 'jackfruit', 'orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple', 'jackfruit']
['orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple', 'jackfruit', 'orange', 'pomegranate', 'jackfruit', 'mango', 'kiwi', 'cherry', 'banana', 'apple', 'jackfruit']

In [ ]:
thislist1

['orange',
 'pomegranate',
 'jackfruit',
 'mango',
 'kiwi',
 'cherry',
 'banana',
 'apple',
 'jackfruit',
 'orange',
 'pomegranate',
 'jackfruit',
 'mango',
 'kiwi',
 'cherry',
 'banana',
 'apple',
 'jackfruit']

In [ ]:
a = [-1, "banana", 0, 50]

for i in a:
  print(i, ',', end = '')

-1 ,banana ,0 ,50 ,

In [ ]:
a = [-1, "banana", 0, 50]

In [ ]:
for i in range(3):
  print(i)

0
1
2

In [ ]:
#Looping Through a List

for i in range(5, 15, 2):
  print(i)

5
7
9
11
13

In [ ]:
for item in thislist1:
  print(item)

NameError: name 'thislist1' is not defined

*Tuple*

In [ ]:
# Init tuple
thistuple = ("apple", "banana", "cherry")
thistuple= tuple(("apple", "banana", "cherry"))

In [ ]:
# Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.

thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

thistuple[1]="mango"

In [ ]:
# But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.

y = list(thistuple)
y[1]="mango"
thistuple = tuple(y)
print(thistuple)

In [ ]:
# Once a tuple is created, you cannot add or remove items.
# To create a tuple with only one item, you have add a comma after the item,
# otherwise Python will not recognize the variable as a tuple.

one_item_tuple = ("mango",)
print(one_item_tuple)

thistuple1 = ("apple")
print(type(thistuple1))

('mango',)
<class 'str'>

In [ ]:
# Concatenating tuple
tuple1 = thistuple + one_item_tuple
print(tuple1)

('apple', 'mango', 'cherry', 'mango')

*Set*

In [ ]:
# A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets.
thisset = {"apple","orange","melon"}
thiset = set(("apple","orange","melon"))
print(thisset)

{'melon', 'apple', 'orange'}

In [ ]:

# You cannot access items in a set by referring to an index, since sets are unordered the items has no index.
# But you can loop through the set items using a for loop, or ask if a specified value is present in a set,
# by using the in keyword.

for x in  thisset:
  print(x)

# Once a set is created, you cannot change its items, but you can add new items.

thisset.add("banana") #insert single items
print(thisset)
thisset.update(["jackfruit","cherry"])
print(thisset)

melon
orange
apple
{'melon', 'orange', 'banana', 'apple'}
{'jackfruit', 'melon', 'cherry', 'banana', 'orange', 'apple'}

In [ ]:
# To remove an item in a set, use the remove(), or the discard() method.
thisset.remove("orange")
thisset.discard("cherry")
print(thisset)

{'jackfruit', 'melon', 'banana', 'apple'}

In [ ]:
# Concatenating two set (union or update)

set1 = {"a", "b" , "2"}
set2 = {"1","2", "3"}
set3 = set1.union(set2)
print(set3)

{'1', '2', 'b', '3', 'a'}

In [ ]:
set1.update(set2) # update() function in set adds elements from a set (passed as an argument) to the set
# Update() method takes only a single argument. The single argument can be a set, list, tuples or a dictionary.
# It automatically converts into a set and adds to the set.
print(set1)

# Set difference() Method Return a set that contains the items that only exist in set1, and not in set2
z = set1.difference(set2)
print(z)

# Return a set that contains the items that exist in both set1, and set2:
z1 = set1.intersection(set2)
print(z1)

{'1', '2', 'b', '3', 'a'}
{'b', 'a'}
{'1', '2', '3'}

*Dictionary*

In [ ]:
# A dictionary is a collection which is unordered, changeable and indexed.
# In Python, dictionaries are written with curly brackets, and they have keys and values.

thisdict= { "brand": "Ford", "model": "Mustang", "year": 1994}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1994}

In [ ]:
# Accessing items of dictionary
x = thisdict["brand"]
y = thisdict["model"]
print(x,y)

toyota Mustang

In [ ]:
thisdict.keys()

dict_keys(['brand', 'model', 'year'])

In [ ]:
# printing the keys
for x in thisdict:
  print(x)

brand
model
year

In [ ]:
"aldfhlksjad" in thisdict

False

In [ ]:
"brand" in thisdict

True

In [ ]:
## adding new item (key, value)
thisdict['rating'] = 4.5

In [ ]:
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1994, 'rating': 4.5}

In [ ]:
# printing the values
for x in thisdict:
  print(thisdict[x])

# Change a value
thisdict["year"]= 1995

print(thisdict)

# How can you change the key in a dictionary?

Ford
Mustang
1964
{'brand': 'Ford', 'model': 'Mustang', 'year': 1995}


*   <font color = 'lightgreen'>*Random number generation*</font>
*   <font color = 'lightgreen'>*Importing library*</font>

In [ ]:
import random

num = random.random() # Generates a random floating-point number in the interval [0,1)
print(num)

num = random.randint(10, 20) # Generates a random integer from x to y, including the x and y
print(num)

choice = random.choice( ["a",2,"asdf",True,5] )
print(choice)

0.6310939202997491
19
asdf

<font color = 'violet'>**Instaling third party libraries**</font>

*   NumPy
*   Pandas
*   Matplotlib
*   Seaborn

*Installing directly from terminal*

 **pip** is the standard package manager for Python. It allows you to install and manage additional packages that are not part of the Python standard library.

In [ ]:
!pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.19.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (3.2.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (0.11.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.4.1)

*Installing from text file*

Creating a text file in python

In [ ]:
requirementsFile = open("requirements.txt","w+")

In [ ]:
pip install -r /content/requirements.txt

List of Installed packages

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
bigframes                        0.19.0
bleach                           6.1.0
blinker                          1.4
blis                             0.7.11
blosc2                           2.0.0
bokeh                            3.3.3
bqplot                           0.12.42
branca                           0.7.0
build                            1.0.3
CacheControl                     0.13.1
cachetools                       5.3.2
catalogue                        2.0.10
certifi                          2023.11.17
cffi                             1.16.0
chardet                          5.2.0
charset-normalizer               3.3.2
chex                             0.1.7
click                            8.1.7
click-plugins                    1.1.1
cligj                            0.7.2
cloudpickle                      2.2.1
cmake                            3.27.9
cmdstanpy                        1.2.0
colorcet                         3.0.1
colorlover                       0.3.0
colour                           0.1.5
community                        1.0.0b1
confection                       0.1.4
cons                             0.4.6
contextlib2                      21.6.0
contourpy                        1.2.0
cryptography                     41.0.7
cufflinks                        0.17.3
cupy-cuda12x                     12.2.0
cvxopt                           1.3.2
cvxpy                            1.3.2
cycler                           0.12.1
cymem                            2.0.8
Cython                           3.0.8
dask                             2023.8.1
datascience                      0.17.6
db-dtypes                        1.2.0
dbus-python                      1.2.18
debugpy                          1.6.6
decorator                        4.4.2
defusedxml                       0.7.1
diskcache                        5.6.3
distributed                      2023.8.1
distro                           1.7.0
dlib                             19.24.2
dm-tree                          0.1.8
docutils                         0.18.1
dopamine-rl                      4.0.6
duckdb                           0.9.2
earthengine-api                  0.1.385
easydict                         1.11
ecos                             2.0.12
editdistance                     0.6.2
eerepr                           0.0.4
en-core-web-sm                   3.6.0
entrypoints                      0.4
et-xmlfile                       1.1.0
etils                            1.6.0
etuples                          0.3.9
exceptiongroup                   1.2.0
fastai                           2.7.13
fastcore                         1.5.29
fastdownload                     0.0.7
fastjsonschema                   2.19.1
fastprogress                     1.0.3
fastrlock                        0.8.2
filelock                         3.13.1
fiona                            1.9.5
firebase-admin                   5.3.0
Flask                            2.2.5
flatbuffers                      23.5.26
flax                             0.7.5
folium                           0.14.0
fonttools                        4.47.2
frozendict                       2.4.0
frozenlist                       1.4.1
fsspec                           2023.6.0
future                           0.18.3
gast                             0.5.4
gcsfs                            2023.6.0
GDAL                             3.4.3
gdown                            4.6.6
geemap                           0.30.3
gensim                           4.3.2
geocoder                         1.38.1
geographiclib                    2.0
geopandas                        0.13.2
geopy                            2.3.0
gin-config                       0.5.0
glob2                            0.7
google                           2.0.3
google-ai-generativelanguage     0.4.0
google-api-core                  2.11.1
google-api-python-client         2.84.0
google-auth                      2.17.3
google-auth-httplib2             0.1.1
google-auth-oauthlib             1.2.0
google-cloud-aiplatform          1.39.0
google-cloud-bigquery            3.12.0
google-cloud-bigquery-connection 1.12.1
google-cloud-bigquery-storage    2.24.0
google-cloud-core                2.3.3
google-cloud-datastore           2.15.2
google-cloud-firestore           2.11.1
google-cloud-functions           1.13.3
google-cloud-iam                 2.13.0
google-cloud-language            2.9.1
google-cloud-resource-manager    1.11.0
google-cloud-storage             2.8.0
google-cloud-translate           3.11.3
google-colab                     1.0.0
google-crc32c                    1.5.0
google-generativeai              0.3.2
google-pasta                     0.2.0
google-resumable-media           2.7.0
googleapis-common-protos         1.62.0
googledrivedownloader            0.4
graphviz                         0.20.1
greenlet                         3.0.3
grpc-google-iam-v1               0.13.0
grpcio                           1.60.0
grpcio-status                    1.48.2
gspread                          3.4.2
gspread-dataframe                3.3.1
gym                              0.25.2
gym-notices                      0.0.8
h5netcdf                         1.3.0
h5py                             3.9.0
holidays                         0.40
holoviews                        1.17.1
html5lib                         1.1
httpimport                       1.3.1
httplib2                         0.22.0
huggingface-hub                  0.20.2
humanize                         4.7.0
hyperopt                         0.2.7
ibis-framework                   7.1.0
idna                             3.6
imageio                          2.31.6
imageio-ffmpeg                   0.4.9
imagesize                        1.4.1
imbalanced-learn                 0.10.1
imgaug                           0.4.0
importlib-metadata               7.0.1
importlib-resources              6.1.1
imutils                          0.5.4
inflect                          7.0.0
iniconfig                        2.0.0
install                          1.3.5
intel-openmp                     2023.2.3
ipyevents                        2.0.2
ipyfilechooser                   0.6.0
ipykernel                        5.5.6
ipyleaflet                       0.18.1
ipython                          7.34.0
ipython-genutils                 0.2.0
ipython-sql                      0.5.0
ipytree                          0.2.2
ipywidgets                       7.7.1
itsdangerous                     2.1.2
jax                              0.4.23
jaxlib                           0.4.23+cuda12.cudnn89
jeepney                          0.7.1
jieba                            0.42.1
Jinja2                           3.1.3
joblib                           1.3.2
jsonpickle                       3.0.2
jsonschema                       4.19.2
jsonschema-specifications        2023.12.1
jupyter-client                   6.1.12
jupyter-console                  6.1.0
jupyter_core                     5.7.1
jupyter-server                   1.24.0
jupyterlab_pygments              0.3.0
jupyterlab-widgets               3.0.9
kaggle                           1.5.16
kagglehub                        0.1.5
keras                            2.15.0
keyring                          23.5.0
kiwisolver                       1.4.5
langcodes                        3.3.0
launchpadlib                     1.10.16
lazr.restfulclient               0.14.4
lazr.uri                         1.0.6
lazy_loader                      0.3
libclang                         16.0.6
librosa                          0.10.1
lida                             0.0.10
lightgbm                         4.1.0
linkify-it-py                    2.0.2
llmx                             0.0.15a0
llvmlite                         0.41.1
locket                           1.0.0
logical-unification              0.4.6
lxml                             4.9.4
malloy                           2023.1067
Markdown                         3.5.2
markdown-it-py                   3.0.0
MarkupSafe                       2.1.3
matplotlib                       3.7.1
matplotlib-inline                0.1.6
matplotlib-venn                  0.11.9
mdit-py-plugins                  0.4.0
mdurl                            0.1.2
miniKanren                       1.0.3
missingno                        0.5.2
mistune                          0.8.4
mizani                           0.9.3
mkl                              2023.2.0
ml-dtypes                        0.2.0
mlxtend                          0.22.0
more-itertools                   10.1.0
moviepy                          1.0.3
mpmath                           1.3.0
msgpack                          1.0.7
multidict                        6.0.4
multipledispatch                 1.0.0
multitasking                     0.0.11
murmurhash                       1.0.10
music21                          9.1.0
natsort                          8.4.0
nbclassic                        1.0.0
nbclient                         0.9.0
nbconvert                        6.5.4
nbformat                         5.9.2
nest-asyncio                     1.5.8
networkx                         3.2.1
nibabel                          4.0.2
nltk                             3.8.1
notebook                         6.5.5
notebook_shim                    0.2.3
numba                            0.58.1
numexpr                          2.8.8
numpy                            1.23.5
oauth2client                     4.1.3
oauthlib                         3.2.2
opencv-contrib-python            4.8.0.76
opencv-python                    4.8.0.76
opencv-python-headless           4.9.0.80
openpyxl                         3.1.2
opt-einsum                       3.3.0
optax                            0.1.7
orbax-checkpoint                 0.4.4
osqp                             0.6.2.post8
packaging                        23.2
pandas                           1.5.3
pandas-datareader                0.10.0
pandas-gbq                       0.19.2
pandas-stubs                     1.5.3.230304
pandocfilters                    1.5.0
panel                            1.3.6
param                            2.0.1
parso                            0.8.3
parsy                            2.1
partd                            1.4.1
pathlib                          1.0.1
pathy                            0.10.3
patsy                            0.5.6
peewee                           3.17.0
pexpect                          4.9.0
pickleshare                      0.7.5
Pillow                           9.4.0
pins                             0.8.4
pip                              23.1.2
pip-tools                        6.13.0
platformdirs                     4.1.0
plotly                           5.15.0
plotnine                         0.12.4
pluggy                           1.3.0
polars                           0.17.3
pooch                            1.8.0
portpicker                       1.5.2
prefetch-generator               1.0.3
preshed                          3.0.9
prettytable                      3.9.0
proglog                          0.1.10
progressbar2                     4.2.0
prometheus-client                0.19.0
promise                          2.3
prompt-toolkit                   3.0.43
prophet                          1.1.5
proto-plus                       1.23.0
protobuf                         3.20.3
psutil                           5.9.5
psycopg2                         2.9.9
ptyprocess                       0.7.0
py-cpuinfo                       9.0.0
py4j                             0.10.9.7
pyarrow                          10.0.1
pyarrow-hotfix                   0.6
pyasn1                           0.5.1
pyasn1-modules                   0.3.0
pycocotools                      2.0.7
pycparser                        2.21
pyct                             0.5.0
pydantic                         1.10.13
pydata-google-auth               1.8.2
pydot                            1.4.2
pydot-ng                         2.0.0
pydotplus                        2.0.2
PyDrive                          1.3.1
PyDrive2                         1.6.3
pyerfa                           2.0.1.1
pygame                           2.5.2
Pygments                         2.16.1
PyGObject                        3.42.1
PyJWT                            2.3.0
pymc                             5.7.2
pymystem3                        0.2.0
PyOpenGL                         3.1.7
pyOpenSSL                        23.3.0
pyparsing                        3.1.1
pyperclip                        1.8.2
pyproj                           3.6.1
pyproject_hooks                  1.0.0
pyshp                            2.3.1
PySocks                          1.7.1
pytensor                         2.14.2
pytest                           7.4.4
python-apt                       0.0.0
python-box                       7.1.1
python-dateutil                  2.8.2
python-louvain                   0.16
python-slugify                   8.0.1
python-utils                     3.8.1
pytz                             2023.3.post1
pyviz_comms                      3.0.0
PyWavelets                       1.5.0
PyYAML                           6.0.1
pyzmq                            23.2.1
qdldl                            0.1.7.post0
qudida                           0.0.4
ratelim                          0.1.6
referencing                      0.32.1
regex                            2023.6.3
requests                         2.31.0
requests-oauthlib                1.3.1
requirements-parser              0.5.0
rich                             13.7.0
rpds-py                          0.16.2
rpy2                             3.4.2
rsa                              4.9
safetensors                      0.4.1
scikit-image                     0.19.3
scikit-learn                     1.2.2
scipy                            1.11.4
scooby                           0.9.2
scs                              3.2.4.post1
seaborn                          0.13.1
SecretStorage                    3.3.1
Send2Trash                       1.8.2
setuptools                       67.7.2
shapely                          2.0.2
six                              1.16.0
sklearn-pandas                   2.2.0
smart-open                       6.4.0
sniffio                          1.3.0
snowballstemmer                  2.2.0
sortedcontainers                 2.4.0
soundfile                        0.12.1
soupsieve                        2.5
soxr                             0.3.7
spacy                            3.6.1
spacy-legacy                     3.0.12
spacy-loggers                    1.0.5
Sphinx                           5.0.2
sphinxcontrib-applehelp          1.0.7
sphinxcontrib-devhelp            1.0.5
sphinxcontrib-htmlhelp           2.0.4
sphinxcontrib-jsmath             1.0.1
sphinxcontrib-qthelp             1.0.6
sphinxcontrib-serializinghtml    1.1.9
SQLAlchemy                       2.0.24
sqlglot                          19.9.0
sqlparse                         0.4.4
srsly                            2.4.8
stanio                           0.3.0
statsmodels                      0.14.1
sympy                            1.12
tables                           3.8.0
tabulate                         0.9.0
tbb                              2021.11.0
tblib                            3.0.0
tenacity                         8.2.3
tensorboard                      2.15.1
tensorboard-data-server          0.7.2
tensorflow                       2.15.0
tensorflow-datasets              4.9.4
tensorflow-estimator             2.15.0
tensorflow-gcs-config            2.15.0
tensorflow-hub                   0.15.0
tensorflow-io-gcs-filesystem     0.35.0
tensorflow-metadata              1.14.0
tensorflow-probability           0.22.0
tensorstore                      0.1.45
termcolor                        2.4.0
terminado                        0.18.0
text-unidecode                   1.3
textblob                         0.17.1
tf-slim                          1.1.0
thinc                            8.1.12
threadpoolctl                    3.2.0
tifffile                         2023.12.9
tinycss2                         1.2.1
tokenizers                       0.15.0
toml                             0.10.2
tomli                            2.0.1
toolz                            0.12.0
torch                            2.1.0+cu121
torchaudio                       2.1.0+cu121
torchdata                        0.7.0
torchsummary                     1.5.1
torchtext                        0.16.0
torchvision                      0.16.0+cu121
tornado                          6.3.2
tqdm                             4.66.1
traitlets                        5.7.1
traittypes                       0.2.1
transformers                     4.35.2
triton                           2.1.0
tweepy                           4.14.0
typer                            0.9.0
types-pytz                       2023.3.1.1
types-setuptools                 69.0.0.20240106
typing_extensions                4.5.0
tzlocal                          5.2
uc-micro-py                      1.0.2
uritemplate                      4.1.1
urllib3                          2.0.7
vega-datasets                    0.9.0
wadllib                          1.3.6
wasabi                           1.1.2
wcwidth                          0.2.13
webcolors                        1.13
webencodings                     0.5.1
websocket-client                 1.7.0
Werkzeug                         3.0.1
wheel                            0.42.0
widgetsnbextension               3.6.6
wordcloud                        1.9.3
wrapt                            1.14.1
xarray                           2023.7.0
xarray-einstats                  0.6.0
xgboost                          2.0.3
xlrd                             2.0.1
xxhash                           3.4.1
xyzservices                      2023.10.1
yarl                             1.9.4
yellowbrick                      1.5
yfinance                         0.2.35
zict                             3.0.0
zipp                             3.17.0

<font color = orange> NumPy </font> <br>

---


The best source to know about any third party library is it's documentation.

[Numpy Documentation](https://numpy.org/doc/)

NumPy is a Python library used for working with arrays. NumPy is short for "Numerical Python".
NumPy aims to provide an array object that is up to 30x faster than traditional Python lists. It is mainly used for large multi-dimensional array and matrix processing.

In [ ]:
import numpy as np  # importing libraries

arr0 = np.array(23)
print(arr0)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
arr2 = np.array([ [1, 2, 3,5] , [4, 5, 6, 8] ])
print(arr2)

23
[1 2 3 4 5]
[[1 2 3 5]
 [4 5 6 8]]

In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>

In [ ]:
print(arr2.ndim) # no of dimensions
print(arr2[1,0])
print(arr2[1,-1])

2
4
8

In [ ]:
#again slicing

#[start:end:step].
print(arr2[1 , 0:2])

print(arr2[1,::3])

print(arr2.dtype) # data type

[4 5]
[4 8]
int64

*Numpy array shapes*

In [ ]:
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

print(arr2.shape)
print(type(arr2.shape))

(2, 4)
<class 'tuple'>

In [ ]:
#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)
newarr1 = arr.reshape(2, 3, 2)
print(newarr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

In [ ]:
arr.shape

(12,)

In [ ]:
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
newarr3 = newarr1.reshape(-1)
print(newarr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

*Numpy array of Ones and Zeros*

In [ ]:
# The numpy.zeros() function returns a new array of given shape and type, with zeros.
rows, cols = 3,4
arrayZero = np.zeros([3,3])
print(arrayZero)
arrayZero2 = np.zeros([rows,cols])
print(arrayZero2)

arrayOne = np.ones([rows,cols])
print(arrayOne)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

*Random numbers with Numpy*

In [ ]:
x = np.random.rand(2,5) # Random numbers between 0 and 1 (Not-Included) # shape (2,5)
print(x)

y = np.random.randint(1,20, size = (3,3)) # Random integers within pecified range
print(y)

z = np.random.randn(2,5)
print(z)

[[0.22876246 0.34787806 0.1836659  0.46077745 0.22998727]
 [0.86986159 0.42637238 0.55972309 0.2788355  0.29670499]]
[[17 13 16]
 [ 4  1  3]
 [ 4  7 18]]
[[ 1.08719996e+00  3.77405770e-01  1.86415810e+00  5.41311024e-01
  -1.53020213e+00]
 [ 1.06287214e-03  2.82436998e-01 -1.59175930e+00  7.76009722e-01
  -5.40429642e-01]]

In [ ]:
a = np.eye(5) # Identity
print(a)
a1 = np.eye(2, 3)
print(a1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]

In [ ]:
c = np.transpose(a1)
print(c)

print(np.matmul(c, np.transpose(c))) # Matrix Mutiplication

<font color = 'orange'>**Pandas**</font><br>

---


*pandas* is a Python package providing fast, flexible, and expressive data structures designed to work with relational or labeled data both. It is a fundamental high-level building block for doing practical, real world data analysis in Python.<br>
*pandas* is well suited for tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet.

In [ ]:
import pandas as pd # Importing library

**DataFrame**<br>
A DataFrame is a tabular data structure, encapsulating multiple series like columns in a spreadsheet. Data are stored internally as a 2-dimensional object, but the DataFrame allows us to represent and manipulate higher-dimensional data.

In [ ]:
# Initializing a DataFrame

data = pd.DataFrame({'value':[632, 1638, 569, 115, 433, 1130, 754, 555],
                     'patient':[1, 1, 1, 1, 2, 2, 2, 2],
                     'phylum':['Firmicutes', 'Proteobacteria', 'Actinobacteria',
    'Bacteroidetes', 'Firmicutes', 'Proteobacteria', 'Actinobacteria', 'Bacteroidetes']})
data

   value  patient          phylum
0    632        1      Firmicutes
1   1638        1  Proteobacteria
2    569        1  Actinobacteria
3    115        1   Bacteroidetes
4    433        2      Firmicutes
5   1130        2  Proteobacteria
6    754        2  Actinobacteria
7    555        2   Bacteroidetes

In [ ]:
# We can change the order by indexing them in the order we desire.
data = data[['phylum','value','patient']]
data

           phylum  value  patient
0      Firmicutes    632        1
1  Proteobacteria   1638        1
2  Actinobacteria    569        1
3   Bacteroidetes    115        1
4      Firmicutes    433        2
5  Proteobacteria   1130        2
6  Actinobacteria    754        2
7   Bacteroidetes    555        2

In [ ]:
# print(data.columns) # Printing column names
print(data.dtypes) # Printing column types

phylum     object
value       int64
patient     int64
dtype: object

In [ ]:
print(data['patient']) # Printing single column

0    1
1    1
2    1
3    1
4    2
5    2
6    2
7    2
Name: patient, dtype: int64

In [ ]:
print(data.iloc[0]) # Printing single row
print(len(data)) # Total number of rows

phylum     Firmicutes
value             632
patient             1
Name: 0, dtype: object
8

In [ ]:
# Iterating DataFrame
for i in range(0, len(data)):
  print(data.iloc[i])

phylum     Firmicutes
value             632
patient             1
Name: 0, dtype: object
phylum     Proteobacteria
value                1638
patient                 1
Name: 1, dtype: object
phylum     Actinobacteria
value                 569
patient                 1
Name: 2, dtype: object
phylum     Bacteroidetes
value                115
patient                1
Name: 3, dtype: object
phylum     Firmicutes
value             433
patient             2
Name: 4, dtype: object
phylum     Proteobacteria
value                1130
patient                 2
Name: 5, dtype: object
phylum     Actinobacteria
value                 754
patient                 2
Name: 6, dtype: object
phylum     Bacteroidetes
value                555
patient                2
Name: 7, dtype: object

In [ ]:
# An alternative way of initializing a DataFrame is with a list of dictionaries.

data = pd.DataFrame([{ 'phylum': 'Firmicutes', 'patient': 1, 'value': 632},
                    {'patient': 1, 'value': 1638, 'phylum': 'Proteobacteria'},
                    {'patient': 1, 'phylum': 'Actinobacteria', 'value': 569},
                    {'patient': 1, 'phylum': 'Bacteroidetes', 'value': 115},
                    {'patient': 2, 'phylum': 'Firmicutes', 'value': 433},
                    {'patient': 2, 'phylum': 'Proteobacteria', 'value': 1130},
                    {'patient': 2, 'phylum': 'Actinobacteria', 'value': 754},
                    {'patient': 2, 'phylum': 'Bacteroidetes', 'value': 555}])

data

           phylum  patient  value
0      Firmicutes        1    632
1  Proteobacteria        1   1638
2  Actinobacteria        1    569
3   Bacteroidetes        1    115
4      Firmicutes        2    433
5  Proteobacteria        2   1130
6  Actinobacteria        2    754
7   Bacteroidetes        2    555

In [ ]:
# Each row in a DataFrame is an object. We can change the row data as following.
data.patient[0] = 500
data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   patient          phylum  value
0      500      Firmicutes    632
1        1  Proteobacteria   1638
2        1  Actinobacteria    569
3        1   Bacteroidetes    115
4        2      Firmicutes    433
5        2  Proteobacteria   1130
6        2  Actinobacteria    754
7        2   Bacteroidetes    555

In [ ]:
# Copy and Modify

patients = data.patient.copy()
patients[1] = 200
print(data)
print("---------")
print(patients)

   patient          phylum  value
0      500      Firmicutes    632
1        1  Proteobacteria   1638
2        1  Actinobacteria    569
3        1   Bacteroidetes    115
4        2      Firmicutes    433
5        2  Proteobacteria   1130
6        2  Actinobacteria    754
7        2   Bacteroidetes    555
---------
0    500
1    200
2      1
3      1
4      2
5      2
6      2
7      2
Name: patient, dtype: int64

In [ ]:
# Adding a column
data['year'] = 2021
data

   patient          phylum  value  year
0      500      Firmicutes    632  2021
1        1  Proteobacteria   1638  2021
2        1  Actinobacteria    569  2021
3        1   Bacteroidetes    115  2021
4        2      Firmicutes    433  2021
5        2  Proteobacteria   1130  2021
6        2  Actinobacteria    754  2021
7        2   Bacteroidetes    555  2021

**Downloading Dataset**

In [ ]:
!gdown --id 1yniDu31JGo7-Df7Zt9N_9n89i90Ot74W

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/gdown/cli.py", line 151, in main
    filename = download(
  File "/usr/local/lib/python3.10/dist-packages/gdown/download.py", line 203, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Decompressing files**

In [ ]:
!unzip /content/TitanicDS.zip

Archive:  /content/TitanicDS.zip
  inflating: test.csv
  inflating: train.csv

Reading from CSV using Pandas

In [ ]:
train = pd.read_csv('/content/train.csv')

In [ ]:
# Information about first six rows - Including header
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Condition on column values
new_train = train[ (train.Age>30) & (train.Survived==1) ]
new_train

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1              2         1       1  ...  71.2833   C85         C
3              4         1       1  ...  53.1000  C123         S
11            12         1       1  ...  26.5500  C103         S
21            22         1       2  ...  13.0000   D56         S
52            53         1       1  ...  76.7292   D33         C
..           ...       ...     ...  ...      ...   ...       ...
835          836         1       1  ...  83.1583   E49         C
857          858         1       1  ...  26.5500   E17         S
862          863         1       1  ...  25.9292   D17         S
871          872         1       1  ...  52.5542   D35         S
879          880         1       1  ...  83.1583   C50         C

[70 rows x 12 columns]

In [ ]:
# Adding a new Column
randomCol = []
for i in range(0, len(new_train)):
  randomCol.append(random.randint(0,100))

new_train['Randomness'] = randomCol
new_train

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     PassengerId  Survived  Pclass  ... Cabin Embarked  Randomness
1              2         1       1  ...   C85        C          77
3              4         1       1  ...  C123        S          42
11            12         1       1  ...  C103        S          82
21            22         1       2  ...   D56        S          49
52            53         1       1  ...   D33        C          65
..           ...       ...     ...  ...   ...      ...         ...
835          836         1       1  ...   E49        C          11
857          858         1       1  ...   E17        S           5
862          863         1       1  ...   D17        S          16
871          872         1       1  ...   D35        S          84
879          880         1       1  ...   C50        C          30

[70 rows x 13 columns]

In [ ]:
# Dropping a column
new_train.drop(labels=['Randomness'], inplace=True, axis = 1)
new_train

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
# Dropping a row
new_train.drop(labels=[1,3], inplace=True, axis=0)
new_train

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
11            12         1       1  ...  26.5500  C103         S
21            22         1       2  ...  13.0000   D56         S
52            53         1       1  ...  76.7292   D33         C
123          124         1       2  ...  13.0000  E101         S
194          195         1       1  ...  27.7208    B4         C
..           ...       ...     ...  ...      ...   ...       ...
835          836         1       1  ...  83.1583   E49         C
857          858         1       1  ...  26.5500   E17         S
862          863         1       1  ...  25.9292   D17         S
871          872         1       1  ...  52.5542   D35         S
879          880         1       1  ...  83.1583   C50         C

[68 rows x 12 columns]